# Generated by Django 6.1.1 on 2026-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetics_space', '0002_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
