# Generated by Django 6.1.1 on 2026-09-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetics_space', '0006_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='taken_pn',
            new_name='taken_on',
        ),
    ]
