# Generated by Django 6.1.1 on 2026-09-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetics_space', '0007_rename_taken_pn_log_taken_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='TIME',
            new_name='time',
        ),
    ]
